### ISSUE TITLE
Upravit eventy - stare eventy nemaji GPS souradnice

### ISSUE THREAD

**Issue by janzhanal** [otahirs/zbm_web#1]
Při procházení jsem vybrala Upravit eventy a po zobrazení již zadané události (Dvorská bouda) jsem dala Uložit a vyskočila mi chyba, že není správně zadaná GPS (žádná tam nebyla, ani v původní tabulce), asi by neměla být povinná?

Jak pise lenka budto nepovinna nebo nejaka defaultni hodnota nekde v oceanu :)

**Comment by otahirs** [comment]
php pro GPS opraveno na
`if(isset($_POST["GPS"])`**`&& trim($_POST["GPS"]) != ""`**`)`
