### ISSUE TITLE
skupina hobby

### ISSUE THREAD

**Issue by drbca** [otahirs/zbm_web#106]
Ahoj Oto,

mohl bych poprosit o přídání do levné lišty odkaz novou skupinu "Hobby"?
Info:
Hobík je, kdo jde rád do lesa s mapou. Nepotřebuje už vyhrát, ale chce, aby ho závod bavil. A třeba by chtěl se vyvarovat chyby, kterou udělá každou sobotu.
Věk: ?? - 99
Společný e-mail: zabiny_hobby@googlegroups.com

Děkuji

**Comment by janzhanal** [comment]
Ahoj, 
urcite udelej mailing list 
@zabiny.club

**Comment by drbca** [comment]
To by bylo super hobby@zabiny.club
To mě nenapadlo, že by to šlo. Tak tuhle zruším. ;)

**Comment by janzhanal** [comment]
vytvoril jsem ti mail a skupinu na google. Lidi bys mel zvladnout naklikat v groups.google.com po prihlaseni pres zavody@zabiny.club.

Spravne pridani na stranky proberu s Otikem. (@otahirs je pocet skupin zmenitelny)

**Comment by otahirs** [comment]
všechno jde, na druhou stranu ten ňouma co to navrhoval s rozšiřitelností moc nepočítal, takže pár úprav tam bude.
@drbca  obecně k úpravám stránek se dostanu v půlce června, kdy budu mít po zkouškách. 
(@janzhanal můžete si zatím určit prioritu co by se hodilo upravit/přidat nejvíce)

**Comment by janzhanal** [comment]
@drbca, co vse pro skupinu hobby potrebujeme? To stejne, co pro ostatni?
(kalendar, filtr v nem, akce, tydenni plan, uvodni stranka)

**Comment by drbca** [comment]
Asi jo. Tedy nevím, jestli všechny záložky využiji, ale mají to i žabičky, tak proč ne? Třeba se to někdy bude hodit. 
Díky

**Comment by janzhanal** [comment]
OK, v jakem poradi to potrebujeme mit hotove?

**Comment by drbca** [comment]
Zatím je tne e-mail, to mi stačí. Nehoří to.

**Comment by otahirs** [comment]
ok?

**Comment by drbca** [comment]
Gratuluji k úspěšným zkouškám!
A díky! Vypadá to suprově. Zavírám.
