### ISSUE TITLE
Další užitečné kontakty

### ISSUE THREAD

**Issue by drbca** [otahirs/zbm_web#107]
Prosím o změnu e-mailu:
Další užitečné kontakty:

Přihlášky na závody: Jan Drábek - drbca@centrum.cz
 - změnit na 
 - prihlasky@zabiny.club 

Někd eje můj a někde tohle...

A druhá věc. Mohl by existovat nějaký e-mail dohlasky@zabiny.club? Který by se dával do pokynů a všude a používal by ho ten, kdo by měl na starost zrovna it/prezentaci na závodech? 
Díky

**Comment by janzhanal** [comment]
Vytvoril jsem google uzivatele zavody@zabiny.club, heslo mas na Slacku

**Comment by drbca** [comment]
Díky!
