### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by jakub-h** [otahirs/zbm_web#12]
U kontaktu (úplně dole) by to chtělo krom mailu i jméno a třeba funkci, ať lidi ví, komu píšou. Případně rovnou víc kontaktů na různý lidi. Asi není nutný, aby úplně všechno šlo přes Libina. Kontakty na trenéry jednotlivých skupin v jejich sekcích?

EDIT: Všiml jsem si, že máme samostatnou stránku s kontakty, sorry. Nicméně ten jeden random mail na spodku navbaru by to chtělo nějak pojmenovat.

**Comment by otahirs** [comment]
kontakty na trenéry  v sekcích budou
