### ISSUE TITLE
Aktualizace informací na webu (Finance)

### ISSUE THREAD

**Issue by alfik-alfik** [otahirs/zbm_web#124]
Prosím o aktualizaci informací v sekci Informace -> Finance. V části Kolik zaplatím aktualizovat tabulkou v příloze nebo zde [https://docs.google.com/document/d/1popBhqTk-QY0sLRs6RRsizsCJzknoOecO0-LcxH2eNg/edit?usp=sharing]
[Členské příspěvky 2022 web.zip](https://github.com/otahirs/zbm_web/files/7837269/Clenske.prispevky.2022.web.zip)
.

**Comment by otahirs** [comment]
co úvodní informace viz https://zabiny.club/informace#prispevky ?
> Členské příspěvky je potřeba zaplatit **nejpozději do 26.&nbsp;2.&nbsp;2021**. Zároveň v Přihláškovém systému vyplňte “závod” - _Oddílové příspěvky 2021 - evidence_, dle příslušného typu příspěvku.
> 
> Platby proveďte bezhotovostně na účet SK Brno-Žabovřesky u Raifeisenbank 4067843369/5500, vs. xxxx (kde xxxx = registrační číslo).
> 
> Ve všech typech příspěvků jsou již zahrnuty povinné odvody SK ve výši 300,–&nbsp;Kč a registrace ČSOS ve výši 100,–&nbsp;Kč.
> 
> Vyúčtování předchozího roku vidíte aktuálně v Přihláškovém systému. Veškeré dluhy z minulosti je potřeba vyrovnat taktéž nejpozději do 26. 2. 2021. Členové, kteří nevyrovnají dlužné částky z minulého období či nezaplatí oddílové příspěvky, nebudou přihlašováni na závody!Vyúčtování předchozího roku vidíte aktuálně v Přihláškovém systému. Veškeré **dluhy** z minulosti je potřeba vyrovnat taktéž nejpozději **do 26.&nbsp;2.&nbsp;2021**. Členové, kteří nevyrovnají dlužné částky z minulého období či nezaplatí oddílové příspěvky, **nebudou přihlašováni na závody!**

**Comment by alfik-alfik** [comment]
Ty prosím také datumy a název závody - kopíruji jen relevantní odstavce:
Členské příspěvky je potřeba zaplatit nejpozději do 20. 2. 2022. Zároveň v Přihláškovém systému vyplňte “závod” - _Oddílové příspěvky 2022 - evidence_, dle příslušného typu příspěvku.
.....
Vyúčtování předchozího roku vidíte aktuálně v Přihláškovém systému. Veškeré dluhy z minulosti je potřeba vyrovnat taktéž nejpozději do 20. 2. 2022. Členové, kteří nevyrovnají dlužné částky z minulého období či nezaplatí oddílové příspěvky, nebudou přihlašováni na závody!Vyúčtování předchozího roku vidíte aktuálně v Přihláškovém systému. Veškeré **dluhy** z minulosti je potřeba vyrovnat taktéž nejpozději **do 20. 2. 2022**. Členové, kteří nevyrovnají dlužné částky z minulého období či nezaplatí oddílové příspěvky, **nebudou přihlašováni na závody!**

**Comment by otahirs** [comment]
https://zabiny.club/informace#prispevky

**Comment by alfik-alfik** [comment]
Díky za rychlost, ale ještě jsem našel drobné chybky a rozšíření zveřejněné tabulky o jeden sloupec, prosím o jejich opravu či doplnění - viz. přiložený obrázek s komentáři.
![Příspěvky 2022](https://user-images.githubusercontent.com/61544056/148784584-b4a78214-9d3a-4b50-b89c-8c38de7cbaa6.png)

**Comment by alfik-alfik** [comment]
Nebo mám založit "New issue"?

**Comment by otahirs** [comment]
dodělám

**Comment by otahirs** [comment]
sloupeček po všech slevách by obsahova 12 řádků

**Comment by alfik-alfik** [comment]
Navrhuji provést takto - viz. přiložený obrázek.
![Příspěvky 2022 2](https://user-images.githubusercontent.com/61544056/148890991-a3082a3f-3789-4a5a-b53f-d82b77eb076c.png)

A ještě data ke zkopírování:

ČP s bonusy
1500 Kč
2500 – 3000 Kč
3200 – 3500 Kč
3200 – 5000 Kč
1500 Kč
4000 Kč

**Comment by alfik-alfik** [comment]
Díky. Super.
