### ISSUE TITLE
Rozcestník na fotogalerii přímo na stránkách

### ISSUE THREAD

**Issue by drbca** [otahirs/zbm_web#125]
Ahoj,

myslíš, že by bylo možné, aby na stránkách vznikla nová záložka - _Žabiňácké fotoalbum_, kam by šly dávat odkazy na fotografie?
Já sice založil to album na rajčeti, ale tam ty fotky jsou fakt malé a samá reklama. Lepší by byly, kdyby ty alba byla třeba na googlu a na těch našich stránkách byl jen rozcestník na různá alba.
Co myslíš, šlo by to?

Díky
Drbča

**Comment by janzhanal** [comment]
Na google to neni uplne optimalni, spis to chce najit jinou platformu na sdileni fotek.

**Comment by janzhanal** [comment]
Navrhuju Zoneramu, prozkoumame.

**Comment by janzhanal** [comment]
Closed by #142

**Comment by janzhanal** [comment]
Closed by https://github.com/otahirs/zbm_web/pull/142
