### ISSUE TITLE
Novinky na facebook stránku

### ISSUE THREAD

**Issue by janzhanal** [otahirs/zbm_web#126]
Ahoj, 
protože Adam založil facebook stránku oddílu, myslím, že je potřeba ji začít nějak plnit.
Aspoň automatickým transferem novinek.

Teoreticky by fakebook mohl být i řešením fotogalerie z #125

**Comment by drbca** [comment]
Adamův komentář:
No tak spíš by bylo dobré si říct, co tam chceme dávat a co má smysl. Ty automaticky přehazované věci odjinud nebudou fungovat. To by bylo spíš jen ať tam něco je..

Kdybych měl někoho k ruce, kdo by se tomu chtěl věnovat a třeba se to naučit, tak bych mohl vymyslet nějakou strategii, co s tím 🙂 Ale pravidelně to plnit asi sám nezvládnu..

Obecně bych se asi mohl víc zapojit do propagace klubu a těch online věcí, kterým rozumím.. Když bych míval volněji, tak se tomu můžu věnovat, ale nějací pomocníci by se hodili 🙂

**Comment by janzhanal** [comment]
OK, zaviram, zkus se poptat a v navaznosti na to dat pravo zapisu do te fakebook skupiny:
Sasa, Ota, Jachym, Klarka, Standa jsou urcite schopni dodavat veci za dorost+
