### ISSUE TITLE
odkazy na další oddílové stránky 

### ISSUE THREAD

**Issue by drbca** [otahirs/zbm_web#129]

**Comment by drbca** [comment]
Prosím o přidání rozcestníku, odkazů na linky na oddílový Facebook, Instagram, rajče a klidně bych přidal i tu stránku na stravě.

**Comment by drbca** [comment]
Pokud je ten odkaz to nejmenší, tka proč tam stále není? :(

**Comment by drbca** [comment]
Nějaký progress?

**Comment by drbca** [comment]
Deje se neco?

**Comment by janzhanal** [comment]
@drbca muses mi sem prosím přiházet ty správný linky?

**Comment by drbca** [comment]
FB: https://www.facebook.com/zbm.zabiny/
Rajče: https://skzabovresky.rajce.idnes.cz/
Instagram: https://www.instagram.com/zabinyyy/
Krátký den: https://www.instagram.com/kratky_den/

To je snad všechno.
