### ISSUE TITLE
Nahrani polarisu konci chybou

### ISSUE THREAD

**Issue by janzhanal** [otahirs/zbm_web#14]
CHYBA!!
{"error":{"type":"Twig\\Error\\RuntimeError","message":"An exception has been thrown during the rendering of a template (\"finfo_file(): Empty filename or path\") in \"@Page:\/var\/www\/html\/zbm\/user\/pages\/php\/polaris\" at line 1.","file":"\/var\/www\/html\/zbm\/vendor\/twig\/twig\/src\/Template.php","line":469}}

![Selection_006](https://user-images.githubusercontent.com/34436593/65035653-05d28200-d94a-11e9-8dfd-fc3c445ce5f7.png)

**Comment by otahirs** [comment]
zvětšen limit na php upload, časem dodělám správný error
