### ISSUE TITLE
Kontakty - skupina hobby

### ISSUE THREAD

**Issue by drbca** [otahirs/zbm_web#154]
Ahoj,

prosímo o rozšíření skupiny hobby i na Adama Juráka kontakt@adamjurak.cz.
https://zabiny.club/kontakty
<img width="553" alt="Screenshot 2024-08-06 at 10 17 36" src="https://github.com/user-attachments/assets/28ac2ae7-42b4-4fae-af1a-75a7dd852a75">
Díky

**Comment by janzhanal** [comment]
Done (uz asi nekdy davno, ze uz si to ani nepamatuju)
