### ISSUE TITLE
Sekce vedeni

### ISSUE THREAD

**Issue by janzhanal** [otahirs/zbm_web#17]
Kdyz na to tak koukam, tak potrebujeme misto, kam budem davat zapisy ze schuzi.
Verejne i neverejne.

**Comment by otahirs** [comment]
Najde své místo v archivu

**Comment by janzhanal** [comment]
No a patri aktualni veci do archivu?

**Comment by otahirs** [comment]
Řekl bych, že vše co se pravidelně nepoužívá patří do archivu. Vždy to můžeš propagovat v novince.

**Comment by janzhanal** [comment]
bude-li to triditelne tak OK

**Comment by otahirs** [comment]
zápisy by měli být ve členské sekci
