### ISSUE TITLE
Chybí mapy vydané oddílem

### ISSUE THREAD

**Issue by otahirs** [otahirs/zbm_web#20]

**Comment by janzhanal** [comment]
Predstava je seznam nebo uloziste?
Z meho pohledu jednoznace uloziste, kde mas po prihlaseni ocd soubory.

**Comment by otahirs** [comment]
Pro začátek seznam jak je na starých stránkách + kontakt na oddiloveho správce map

**Comment by janzhanal** [comment]
ok, tedy navrhuju rozdelit na 2 feature requesty:
- seznam vydanych map
- uloziste map, ktere bude casem dynamicky generovat seznam. (na 2 protoze uloziste bude potrebovat diskuzi o tom, co vse ma umet)

**Comment by janzhanal** [comment]
? https://mapy.orientacnisporty.cz/cs/clubs/zbm

**Comment by janzhanal** [comment]
Muzem tohle issue vyresit pridanim odkazu? Spis teda nevim, do jake sekce to dat... Informace?

**Comment by otahirs** [comment]
plánuju trochu změnit rozložení (vzhled odkazů a tréninkových skupin je TBD), a odkaz na mapy se tam vejde.
![Screenshot_2021-05-18 Novinky SK Žabovřesky Brno](https://user-images.githubusercontent.com/24588500/118623927-ffed0e00-b7c8-11eb-95a7-84629d85a00a.png)

---
 jestli bude někdy úložiště, tak spíš jako součást členské sekce

**Comment by janzhanal** [comment]
Uloziste v tuhle chvili resi google drive...
Zmena rozlozeni vypada OK, pravy horni roh nicmene jeste potrebuje dopracovat :-)
Odkaz na mapy bude timto vyreseny
