### ISSUE TITLE
Podpora feedů (RSS/ATOM)

### ISSUE THREAD

**Issue by nufue** [otahirs/zbm_web#24]
Šlo by prosím do GravCMS doplnit plugin [Feed plugin](https://github.com/getgrav/grav-plugin-feed)? Ať můžu novinky na stránce sledovat přes RSS čtečku a nemusím na web chodit každý den?

**Comment by otahirs** [comment]
Dalo to trochu práce, ale novinky by nyní měli být dostupné přes:
https://zabiny.club/rss.rss
https://zabiny.club/rss.atom
https://zabiny.club/rss.json
