### ISSUE TITLE
Akce soustředění

### ISSUE THREAD

**Issue by janzhanal** [otahirs/zbm_web#31]
Přidal bych nějakým způsobem pole "program" (k diskuzi jak), ale chtělo by to aspoň typy tréninků a kdy který bude.

**Comment by otahirs** [comment]
Pole program tam je (nevím jestli dříve bylo schované), je třeba implementovat podporu markdown pro toto pole?

**Comment by janzhanal** [comment]
Ano pls. No mrkni na nejake starsi soustredeni...
J.

**Comment by janzhanal** [comment]
A ted me napada, nemame pole program v import excelu, takze tam spis nebylo nebo?

**Comment by janzhanal** [comment]
Kazdopadne na strankach to je, takze zaviram :D

**Comment by otahirs** [comment]
náplň = program

**Comment by janzhanal** [comment]
Zapnes na tohle pole markdown prosim? jinak to bude strasne neprehledne
