### ISSUE TITLE
Plan na tyden se chova divne!

### ISSUE THREAD

**Issue by janzhanal** [otahirs/zbm_web#32]
Vyplnil/opravil jsem plan (v nedeli tzn pristi tyden). Mam i zmenenou sablonu. Presto je plan na tento tyden jiny, nez jsem nachystal. Nechapu!

aktualne: PO | dorost+ | kopce | 16:30 | Rosnička
pristi tyden: PO | dorost+ | výběhy (světlo s sebou) | 16:30 | Rosnička  (ted jsem to uz opravil, aby tam bylo co tam patri)
spravne: PO | dorost+ | výběhy (světlo s sebou) | 16:30 | Rosnička

**Comment by otahirs** [comment]
https://github.com/otahirs/zbm_web/commit/4cc3d2bfea8dc3d82062c1a824cd2c5d134eb04d

nastaven správně cron
