### ISSUE TITLE
VEdeni oddilu - kontakty

### ISSUE THREAD

**Issue by janzhanal** [otahirs/zbm_web#43]
Zruseni duplicity v sekci informace:
link z informaci primo do kontaktu
(Zitra udelam)

**Comment by otahirs** [comment]
v informacich neni potreba vubec, ponechany pouze kontakty

**Comment by janzhanal** [comment]
Po dnešním mailu od Arnošta navrhuju nakonec stejně přidat link na kontakty do informací. Převážně pro cizí...
