### ISSUE TITLE
Nelze editovat starší události

### ISSUE THREAD

**Issue by janzhanal** [otahirs/zbm_web#53]
Nefunguje mi jeden link ve starším tréninku, ale v GUI se k němu ani tak nedostanu.
Nicméně zobrazení vyhovuje, možná jen přidat možnost zobrazit starší (ale zase ať nedopadnem jak v členské sekci 😄)

**Comment by otahirs** [comment]
přidána možnost zobrazit i starší události. I dříve to šlo leč trochu nešikovně pokud jsi ve filtru data vybral příslušný měsíc

**Comment by janzhanal** [comment]
Dekuji!
