### ISSUE TITLE
Archiv

### ISSUE THREAD

**Issue by janzhanal** [otahirs/zbm_web#62]
Lidi nedavaji proklik z archivu na akce :-/
Slo by default pri prokliku z archivu zobrazit filtr s predzatrzenym "zobrazit již uplynulé"?

**Comment by otahirs** [comment]
Defaultne mít mít nastavené zobrazit jiz uplynulé dává s plynoucím časem
menší a menší smysl.

Spíš bych se ptal co tam lidé hledají, protože ideální je stav kdy tam
nikdo chodit nemusí. Případně se to dá upravit aby to bylo přívětivější,
ale sám nevím jaké mají lidi use casy/co tam hledají.

**Comment by janzhanal** [comment]
no treba ted stare treninky a mapy k nim

**Comment by otahirs** [comment]
co vim tak krome odkazu nekam na postupy pridavat dokumenty/obrazky/mapy k udalostem nejde, pak muzes myslet archiv nevonek, kretej zatim neni :D

**Comment by janzhanal** [comment]
Priklad: chces jit behat na babu, co posilal danac musis si najit udalost s tim treninkem, kde je link na mapy...

**Comment by otahirs** [comment]
to se zatim pred koronou nikdy neresilo; ted bys mel mit nejaky seznam treninku kam muzes jit, bez toho neco vyhledavat. 
Pokud budeme chtit vzdy udrzovat nejaky seznam událostí/tréninků i s mapama, bude se to resit jinak.

**Comment by janzhanal** [comment]
ok, ale znovu, kdyz jdu do archivu udalosti, neocekavam ze pak musim jeste znovu hledat mezi novymi...

**Comment by otahirs** [comment]
ok, to dává smysl

**Comment by otahirs** [comment]
zcela opraveno 946fb05334a691a5c0f959875037326372ce87b5
