### ISSUE TITLE
Draft

### ISSUE THREAD

**Issue by janzhanal** [otahirs/zbm_web#64]
Pri editaci nutne potrebuju "check box draft", optimalne vcetne nahledu pro prihlaseneho
- události
- novinky
Omlouvam se, ale nejsem schopny to nikdy napsat spravne napoprve.

**Comment by otahirs** [comment]
Nechápu. Máš problém s markdownem a potřebuješ náhled nebo ještě něco jiného?

**Comment by janzhanal** [comment]
Potrebuju draft, protoze ne vsechno napisu okamzite (treba napisu novinku, ulozim, zkontroluju a zjistim, ze potrebuju jeste obrazek.

Nebo udalost - musim vyplnit prvni stranku a ulozit => je videt, ale je nekompletni

**Comment by otahirs** [comment]
U novinky mě napadá implementovat draft, tak že při úpravě by se dalo odkliknout, že se má novinka zvěřejnit, pak by se zobrazovala pouze v auth/novinky s nějakým gafickým rozlišením. Pravděpodobně by však bylo třeba dodělat i možnost změny data.

U událostí by se daly rozlišovat stavy něco jako `published | draft | canceled` a dle toho je (ne)zobrazovat na příslušných místech.

Každopádně je to práce v obou případech :D

**Comment by janzhanal** [comment]
Jasne a uplne presne, taky nerikam, ze to musim mit zitra :-)

**Comment by janzhanal** [comment]
Možná bych to zavřel, v tuhle chvíli dostačuje náhled...

**Comment by otahirs** [comment]
novinky mají náhled, události ne
