### ISSUE TITLE
Diakritika - kalendar

### ISSUE THREAD

**Issue by janzhanal** [otahirs/zbm_web#65]
V kalendari se nektere veci zobrazuji jako:
zavod = sede
a
závod = cervene
Rucne vytvorene jsou sede, importovane cervene

Stejne tak diakritika soustredeni (nevim, jestli by nemelo mit i jinou barvu). Predpokladam, ze je drobny neporadek v zobrazeni / ulozeni souboru v databazi. 

Opravil bych, ale uz to chce mit myslenku za tim.

**Comment by otahirs** [comment]
Barva se vybírá dle typu události, který se nastavuje při importu. Při úpravě/vytvoření události v GUI zatím nemám hotový výběr typu.
Šedou barvu mají tedy události bez zadaného typu, pak je aspoň fallback jména na template stránky, který je bez diakritiky.

**Comment by janzhanal** [comment]
Super, zadny stres z toho...

**Comment by otahirs** [comment]
opraveno e529297d8208f31ae1ded078e05e67f5c0b23b81
