### ISSUE TITLE
Zobrazit i uplynulé události na hlavní stránce

### ISSUE THREAD

**Issue by otahirs** [otahirs/zbm_web#67]
nad sloupcem vpravo na hlavní stránce `blíží se` zobrazit i list několika uplynulých událostí `stalo se`

**Comment by janzhanal** [comment]
A slo by to jen treba nazvem? at to zabira treba jen 3 radky? aby nebylo pro nadchazejici potreba rolovat moc...

**Comment by otahirs** [comment]
Tak je to myšleno
