### ISSUE TITLE
Specha: Stranky TSM

### ISSUE THREAD

**Issue by janzhanal** [otahirs/zbm_web#71]
Ahoj, 
potreboval bych velmi jednoduchou stranku pro TSM Jizni Morava, vzhledem k tomu, ze oblastnima strankama nedisponujeme. Mela by stacit 1 stranka, kterou odrolujes dolu s nejakym menu a #odkazem. Obsah dodam, ramcove:
- seznam clenu
- akce (letos to budou odkazy na oddilove akce)
- program
- mozna nejaky dalsi info 

Uplne staci, co tam ma Mara > www.ob-luhacovice.cz/tsm-a-scm-valassko/menu-id-94.html

tsm.zabiny.club

**Comment by otahirs** [comment]
poznámky?

![Screenshot from 2020-05-08 14-26-13](https://user-images.githubusercontent.com/24588500/81405443-eb971f80-9137-11ea-899a-df5a4f6edea2.png)
![Screenshot_2020-05-08 TSM SK Žabovřesky Brno(1)](https://user-images.githubusercontent.com/24588500/81405449-efc33d00-9137-11ea-88a9-dfe5407561a2.png)

**Comment by janzhanal** [comment]
Vyreseno tsm.zabiny.club
