### ISSUE TITLE
Stránka Kontakty - oddíl další užitečné kontakty

### ISSUE THREAD

**Issue by alfik-alfik** [otahirs/zbm_web#74]
Změn prosím tě z
Finance: Věra Mádlová - vera.madlova@centrum.cz

na
Finance: Aleš Finstrle - ales.finstrle@gmail.com

Případně pokud ještě někde figuruje na stránkách věrka, tak provést stejnou záměnu.

**Comment by otahirs** [comment]
a580277b27251bbdea041e9d3943669bdd95dcf9
