### ISSUE TITLE
editace udalosti - nova okna

### ISSUE THREAD

**Issue by lenkajapko** [otahirs/zbm_web#76]
Možná se jen hůř orientuji, ale když si dám editovat událost, otevře se mi (většinou? - mám pocit, že někdy ne :-)) v novém okně. Pak se podívám, jak se to zobrazuje všem a pomalu se začínám v oknech ztrácet. V jednom se odhlásím a v dalších jsem jako přihlášená, ale ve skutečnosti ne, ... nebylo by uživatelsky příjemnější, kdybych zůstávala stále v jednom okně? Lenka

**Comment by janzhanal** [comment]
Za me je nove okno lepsi. 
A na to jak se to zobrazuje vsem se dusledne divam pres nove privatni okno (new private window), aby mi nic nezstalo v cache prohlizece.

**Comment by lenkajapko** [comment]
OK, dobře, přizpůsobím se :-)
Lenka

Lenka Hrušková
Střední průmyslová škola Brno, p.o.
Purkyňova 97
612 00 Brno

lenka.hruskova@sspbrno.cz (mailto:lenka.hruskova@sspbrno.cz)
Telefon: 541 649 130 (škola)
22. červen 2020 18:45, "Jan Zhanal" <notifications@github.com (mailto:notifications@github.com?to=%22Jan%20Zhanal%22%20<notifications@github.com>)> wrote:
	Za me je nove okno lepsi.
A na to jak se to zobrazuje vsem se dusledne divam pres nove privatni okno (new private window), aby mi nic nezstalo v cache prohlizece.

**Comment by otahirs** [comment]
nové okno se již neotvírá d3a9a8614b0a4fb06276b06fa975bc2da9e22ff6
preview tlačítko přidáno přímo k editaci události 241486f2d22e9fc73f817e62c967be30d96acd25
> A na to jak se to zobrazuje vsem se dusledne divam pres nove privatni okno (new private window), aby mi nic nezstalo v cache prohlizece.
opraveny hlavičky requestu, nyní si prohlížeč vždy zkontroluje, zda není k dispozici novější verze stránky, privátní okno není potřeba
